export const interfaceCopy = {
  vi: {
    skip: 'Đến nội dung chính', language: 'Ngôn ngữ', colors: 'Bảng màu', printedIn: 'Màu mực',
    mainNav: 'Điều hướng chính', mobileNav: 'Điều hướng trên điện thoại', openMenu: 'Mở menu', closeMenu: 'Đóng menu', backTop: 'Về đầu trang',
    heroLabel: 'Giới thiệu Nét Studio', studioArt: 'Vườn sáng tạo: bàn thiết kế, bút ngòi, website và giá vẽ',
    moon: 'Mặt trăng', moonHint: 'Nhấn để đổi pha', moonPhases: ['trăng lưỡi liềm', 'trăng bán nguyệt', 'trăng khuyết', 'trăng tròn'],
    bookmarks: 'dấu trang', deliverables: 'Hạng mục bàn giao', filter: 'Lọc dự án và ghi chú', all: 'Tất cả', collapse: 'Thu gọn', showAll: 'Xem tất cả', contact: 'Cùng bắt đầu',
    noteEmail: 'Email nhận ghi chú', downloadNote: 'Tải ghi chú', invalidEmail: 'Vui lòng kiểm tra địa chỉ email.', noteError: 'Không thể tạo ghi chú. Vui lòng kiểm tra email và thử lại.',
    closeDetail: 'Đóng chi tiết', backPage: 'Trở lại trang', projectItems: 'Hạng mục thiết kế', concept: 'Nghiên cứu concept',
    briefKicker: '04 / Từ ý tưởng đến đề bài', briefTitle: ['Bạn muốn tạo', 'điều gì tiếp theo?'],
    briefIntro: 'Không cần một kế hoạch hoàn chỉnh. Kể về điều bạn đang làm, điều còn vướng và kết quả bạn mong muốn.',
    localNotice: 'Tạo bản brief để lưu và chia sẻ. Tệp tải về thiết bị của bạn; form chưa gửi đến Nét.',
    name: 'Tên của bạn', email: 'Email', service: 'Bạn muốn tạo điều gì?', chooseService: 'Chọn một hướng thiết kế', description: 'Kể một chút về ý tưởng',
    namePlaceholder: 'Tên hoặc tên thương hiệu', descriptionPlaceholder: 'Bạn đang làm gì? Ai sẽ sử dụng? Bạn muốn thay đổi điều gì?', downloadBrief: 'Tạo & tải brief',
    briefSuccess: 'Brief đã được tải xuống. Bạn có thể chỉnh sửa và chia sẻ tệp khi sẵn sàng.', noServer: 'Không cần tài khoản. Không lưu thông tin trên máy chủ.',
    invalidName: 'Vui lòng nhập tên hợp lệ (tối đa 100 ký tự).', invalidService: 'Vui lòng chọn một hướng thiết kế.', invalidDescription: 'Mô tả cần từ 20 đến 3.000 ký tự.',
    briefHeading: 'BRIEF DỰ ÁN — NÉT STUDIO', briefName: 'Họ tên', briefService: 'Hướng thiết kế', briefIdea: 'Ý tưởng của bạn', briefDisclaimer: 'Tệp được tạo trên thiết bị của bạn. Chưa gửi đến studio.',
    categories: ['Tất cả', 'Nhận diện', 'Thiết kế web', 'Minh họa'],
    privacy: { title: 'Quyền riêng tư', body: 'Trang không có tài khoản hay công cụ theo dõi. Brief và ghi chú được tạo trên thiết bị của bạn, không gửi email hoặc nội dung tới máy chủ. Trình duyệt chỉ nhớ lựa chọn ngôn ngữ và bảng màu trên thiết bị này.' },
    demo: { title: 'Về trang này', body: 'Nét là concept cho một xưởng thiết kế thương hiệu, website và minh họa. Các dự án được ghi rõ là nghiên cứu concept; trang không đưa ra lời xác nhận về khách hàng thực. Thiết kế nền được tùy chỉnh từ Engraved Illustration Landing Page Template của Kedhareswer Naidu, với dải minh họa studio bổ sung cho Nét.' },
    noteHeading: 'TRƯỚC KHI BẮT ĐẦU — NÉT STUDIO', noteBody: '1. Bạn đang muốn thay đổi điều gì?\n2. Ai cần sử dụng hoặc nhìn thấy thiết kế?\n3. Điều gì cần giữ lại để vẫn là bạn?\n4. Dự án cần có những hạng mục nào?\n5. Khi nào bạn muốn đưa thiết kế vào sử dụng?',
    noteDisclaimer: 'Ghi chú được tạo trên thiết bị. Email chưa được gửi hay đăng ký nhận thư.',
    pageTitle: 'Nét Studio — Để ý tưởng có hình hài.', pageDescription: 'Xưởng thiết kế thương hiệu, website và minh họa. Khám phá tinh thần Nét, các nghiên cứu concept và tạo brief cho ý tưởng tiếp theo.',
  },
  en: {
    skip: 'Skip to main content', language: 'Language', colors: 'Color palette', printedIn: 'Ink color',
    mainNav: 'Main navigation', mobileNav: 'Mobile navigation', openMenu: 'Open menu', closeMenu: 'Close menu', backTop: 'Back to top',
    heroLabel: 'Introducing Nét Studio', studioArt: 'Creative garden: a design desk, pen nib, website and easels',
    moon: 'Moon', moonHint: 'Press to change its phase', moonPhases: ['waxing crescent', 'first quarter', 'waxing gibbous', 'full moon'],
    bookmarks: 'bookmarks', deliverables: 'Deliverables', filter: 'Filter projects and notes', all: 'All', collapse: 'Show less', showAll: 'Show all', contact: 'Let’s begin',
    noteEmail: 'Email for your notes', downloadNote: 'Download notes', invalidEmail: 'Please check your email address.', noteError: 'Could not create your notes. Check your email and try again.',
    closeDetail: 'Close details', backPage: 'Back to the page', projectItems: 'Design scope', concept: 'Concept study',
    briefKicker: '04 / From an idea to a brief', briefTitle: ['What would you', 'like to make next?'],
    briefIntro: 'You don’t need a finished plan. Tell us what you’re working on, where you’re stuck and what you want to achieve.',
    localNotice: 'Create a brief to keep and share. The file downloads to your device; this form does not send it to Nét.',
    name: 'Your name', email: 'Email', service: 'What would you like to create?', chooseService: 'Choose a design direction', description: 'Tell us about your idea',
    namePlaceholder: 'Your name or brand name', descriptionPlaceholder: 'What are you making? Who is it for? What would you like to change?', downloadBrief: 'Create & download brief',
    briefSuccess: 'Your brief has downloaded. You can edit and share the file whenever you’re ready.', noServer: 'No account needed. Your information is not stored on a server.',
    invalidName: 'Please enter a valid name (up to 100 characters).', invalidService: 'Please choose a design direction.', invalidDescription: 'Your description must be between 20 and 3,000 characters.',
    briefHeading: 'PROJECT BRIEF — NÉT STUDIO', briefName: 'Name', briefService: 'Design direction', briefIdea: 'Your idea', briefDisclaimer: 'Created on your device. Not sent to the studio.',
    categories: ['All', 'Brand identity', 'Web design', 'Illustration'],
    privacy: { title: 'Privacy', body: 'This site has no accounts or tracking tools. Briefs and notes are created on your device; your email and content are not sent to a server. Your browser only remembers your language and color palette preferences on this device.' },
    demo: { title: 'About this site', body: 'Nét is a concept for a brand, web and illustration studio. Projects are clearly identified as concept studies, with no claims of real client work. The visual foundation is adapted from the Engraved Illustration Landing Page Template by Kedhareswer Naidu, with a studio illustration band added for Nét.' },
    noteHeading: 'BEFORE WE BEGIN — NÉT STUDIO', noteBody: '1. What would you like to change?\n2. Who needs to use or see the design?\n3. What needs to stay for it to still feel like you?\n4. What should the project include?\n5. When would you like to put it into use?',
    noteDisclaimer: 'Created on your device. Your email has not been sent or subscribed to a mailing list.',
    pageTitle: 'Nét Studio — Give your ideas a form.', pageDescription: 'A concept studio for brand identity, websites and illustration. Explore Nét’s approach, concept studies and a brief for your next idea.',
  },
};
